# weather api
weather.api.key=${WEATHER_API_KEY}
weather.api.connect.timeout.sec=${WEATHER_CONNECT_TIMEOUT_SEC}
weather.api.uri.weather=https://api.openweathermap.org/data/2.5/weather
weather.api.uri.geo=http://api.openweathermap.org/geo/1.0/direct

# app
app.session.expiration=${SESSION_EXPIRATION}